namespace VisualWinUI3
{
	[default_interface]
	runtimeclass Item : Microsoft.UI.Xaml.Data.INotifyPropertyChanged,Windows.Foundation.IStringable
	{
			Item();
			Int64	PropertyX;
			Int32 Type;
			Double Number0;
			Double Number1;
			Double Number2;
			Int32 Int0;
			String Value0;
			String Name1;
			String Name2;
			Boolean Sel{ get; set; };
			Microsoft.UI.Xaml.Media.Brush ColorX{ get; };
			Windows.Foundation.Collections.IObservableVector<String> xitems;
			Windows.Foundation.Collections.IObservableVector<Item> ComboItems { get; };

	}
}
